Global:
  algorithm: PSE
  use_gpu: false
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 2
  save_model_dir: ./output/det_pse/
  save_epoch_step: 200
  eval_batch_step: [4000,63]
  train_batch_size_per_card: 2
  test_batch_size_per_card: 2
  image_shape: [3, 640, 640]
  reader_yml: ./configs/det/det_pse_icdar15_reader.yml
  pretrain_weights: ./pretrain_models/MobileNetV3_large_x0_5_pretrained/
  checkpoints:
  save_res_path: ./output/det_pse/predicts_pse.txt
  save_inference_dir:

Architecture:
  function: ppocr.modeling.architectures.det_model,DetModel

Backbone:
  function: ppocr.modeling.backbones.det_mobilenet_v3,MobileNetV3
  scale: 0.5
  model_name: large

Head:
  function: ppocr.modeling.heads.det_pse_head,PSEHead
  inner_channels: 96
  out_channels: 6

Loss:
  function: ppocr.modeling.losses.det_pse_loss,PSELoss
  balance_loss: true
  main_loss_type: DiceLoss
  Lambda: 0.7
  ohem_ratio: 3

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.001
  beta1: 0.9
  beta2: 0.999
  decay:
    function: cosine_decay
    step_each_epoch: 63
    total_epoch: 600

PostProcess:
  function: ppocr.postprocess.pse_postprocess,PSEPostProcess
  thresh: 0.7311
  box_thresh: 0.93
  scale: 1000